### ISSUE TITLE
Practice 01 done

### ISSUE THREAD

**Issue by electron2302** [electron2302/Haskell-Practice-01#1]
I finished the assignment 01 and it works but: 
* form negative numbers the gcd from haskell is behaving different the Euklid should (see comment in tests)
* why are we using ghc 8.0.2 if there is already 8.8.3, that gave me problems with my ci

**Comment by mgudemann** [comment]
LGTM
*  differences in gcd with negative numbers depends on how negative remainders are defined. Good solution is to restrict the inputs for the property tests to non-negative numbers.
* `8.0.2` is haskell platform, I thinkg. The devbox has `8.6.5` installed which can be set to be used globablly with stack (see exercise 1). You then should also set the resolve in `stack.yaml` to `14.27`. Feel free to use `8.8.3` but it's not required.
* The plan is to use `8.6.5` for the exercises as default

**Comment by electron2302** [comment]
OK, thank you for the clarification 👍
